name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for reporting your first issue! We appreciate your contribution to the project. Our team will review it and provide assistance as soon as possible."
        pr-message: "Congratulations on submitting your first pull request! Your contribution is valuable to us. Our team will review it and provide feedback or merge it if it meets the project's guidelines. Keep up the great work!"
